config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root 'static_pages#home'
  match '/signup',  to: 'users#new',             via: 'get'
  match '/signin',  to: 'sessions#new',          via: 'get'
  match '/signout', to: 'sessions#destroy',      via: 'delete'
  match 'help',     to: 'static_pages#help',     via: 'get'
  match 'about',    to: 'static_pages#about',    via: 'get'
  match 'contact',  to: 'static_pages#contact',  via: 'get'

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.login = login.downcase }
  before_create :create_remember_token
  validates :login, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }
  validates :first_name, :second_name, :email, presence: true
  has_secure_password
  validates :password, length: { minimum: 6 }
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :avatar,
                                    :content_type => ["image/jpg", "image/jpeg",
                                                      "image/png", "image/gif"]

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(login: params[:login].downcase)
    if user && user.authenticate(params[:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Неверный логин или пароль'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :currect_user, only: [:edit, :update]
  before_action :admin_user, only: [:new, :create, :destroy]

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # sign_in @user # если пользователей будет регестрировать админ, то удалить эту строку
      flash[:success] = "Пользователь успешно зарегестрирован"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Профиль обновлен"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Пользователь удален."
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:login, :first_name, :second_name, :email,
                                   :password, :password_confirmation, :avatar)
    end

    def signed_in_user
      store_location
      redirect_to signin_url, notice: "Пожалуйста, авторизуйтесь." unless signed_in?      
    end

    def currect_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Return the full title on a per-page basis.
  def full_title(page_title)
    base_title = "MAZDA | Сайт проверки знаний"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?    
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def avatar_for(user, size)
    image_tag(user.avatar.url(size), alt: "#{user.first_name} #{user.second_name}",
              class: "avatar-#{size}",
              'data-big': "#{image_tag(user.avatar.url(:medium),
                                       alt: "#{user.first_name} #{user.second_name}",
                                       class: "avatar-medium")}")
  end

  def have_avatar?
    !@user.avatar_file_name.nil?
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://mazda.by/">mazda.by</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "О сайте", about_path %></li>
      <li><%= link_to "Контакты", contact_path %></li>
      <li><a href="http://mazda.by/">Новости</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Тесты Mazda", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "На старт",  root_path %></li>
          <li><%= link_to "Помощь",  help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Пользователи", users_path %></li>
            <li><%= link_to "Текущий пользователь: #{current_user.first_name} #{current_user.second_name}", current_user %></li>

              <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Аккаунт <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Профиль", current_user %></li>
                <li><%= link_to "Настройки", edit_user_path(current_user) %></li>
                <% if current_user.admin? %>
                  <li><%= link_to "Добавить пользователя", signup_path %></li>
                <% end %>
                <li class="divider"></li>
                <li>
                  <%= link_to "Выйти", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Войти", signin_path %></li>
          <% end %> %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script scr="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      Форма содержит <%= @user.errors.count %> ошибок
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'О сайте') %>
<div class="center hero-unit">
  <h1>Информация о сайте</h1>
  <h2>
    Сайт создан в июле 2017 г. Кругликом Михаилом. Он является шеф-тренером
    официального дилера Mazda в РБ. Цель сайта проверка усвоения информации
    сотрудниками центра
  </h2>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Контакты') %>
<div class="center hero-unit">
  <h1>Наши контакты</h1>
  <h2>
    Шеф-тренер: Круглик Михаил Леонидович <br>
    тел: +375291611514 <br>
    email: mihail_kruglik@atlantm.by
  </h2>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, 'Помощь') %>
<h1>Помощь по сайту</h1>
<p>Здесь будет информация об основных правилах пользования сайтом проверки знаний MAZDA</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Добро пожаловать') %>
<div class="center hero-unit">
  <h1>Добро пожаловать на сайт проверки знаний MAZDA</h1>
  <h2>
    Это сайт проверки знаний для специалистов отдела сервиса.
    Здесь представлены различные тесты, охватывающие основные
    теоретические знания в сфере ремонта и обслуживания автомобилей
  </h2>

  <%= link_to "Войти прямо сейчас!", signin_path, class: "btn btn-large btn-primary" %> <br>
  Для регистрации на сайте обратитесь к администратору <br>
  Email: miheykrug@mail.ru
</div>

<%= link_to image_tag("mazda_logo.png", alt: "MAZDA"), 'http://mazda.by/' %>

app/views/users/_user.html.erb
<li>
  <% if user.avatar? %>
      <%= image_tag user.avatar.url(:thumb), size: "52" %>
  <% else %>
      <%= image_tag "mazda_logo.png", alt: "MAZDA", size: "52" %>
  <% end %>
  <%= link_to "#{user.first_name} #{user.second_name}", user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "Вы действительно хотите удалить пользователя?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Редактирование даных пользователя') %>
<h1>Редактирование даных пользователя</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :login, "Логин" %>
      <%= f.text_field :login %>

      <%= f.label :first_name, "Имя" %>
      <%= f.text_field :first_name %>

      <%= f.label :second_name, "Фамилия" %>
      <%= f.text_field :second_name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :avatar, "Аватар" %>
      <% if have_avatar? %>
        <div id="avatar">
          <%= avatar_for(@user, :thumb) %>
        </div>
      <% end %>
      <%= f.file_field :avatar %>

      <%= f.label :password, "Пароль" %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Подтверждение пароля" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Сохранить изменения", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Все пользователи') %>
<h1>Все пользователи</h1>

<%= will_paginate %>
<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

<% if current_user.admin? %>
    <%= link_to "Добавить пользователя", signup_path, class: "btn btn-large btn-primary"%>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Создание нового пользователя') %>
<h1>Создание нового пользователя</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :login, "Логин" %>
      <%= f.text_field :login %>

      <%= f.label :first_name, "Имя" %>
      <%= f.text_field :first_name %>

      <%= f.label :second_name, "Фамилия" %>
      <%= f.text_field :second_name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :avatar, "Аватар" %>
      <%= f.file_field :avatar %>

      <%= f.label :password, "Пароль" %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Подтверждение пароля" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Зарегистрировать пользователя", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= provide(:title, "#{@user.first_name} #{@user.second_name}") %>
<div class="row">
  <aside class="span4">
    <section>
      <% if have_avatar? %>
        <div id="avatar">
          <%= avatar_for(@user, :thumb) %>
        </div>
      <% else %>
          <%= image_tag "mazda_logo.png", alt: "MAZDA" %>
      <% end %>
      <h1>
        <%= @user.first_name %> <%= @user.second_name %>
      </h1>
    </section>
  </aside>
</div>
<%= @user.email %>